# Data with Pandas

In [1]:
import pandas as pd

In [8]:
from pathlib import Path
csv_path = Path("../data/eistage.csv")

df = pd.read_csv(
    csv_path,
    sep=";",                
    skiprows=[0, 1],             
    low_memory=False,       
    encoding="utf-8",       
    usecols=[3, 5, 6],      
    nrows=70,
    names= ["year", "heat_days", "ice_days"],
    parse_dates=["year"]           
)

print(df.shape)
print(df.dtypes)
df.head()

(70, 3)
year         datetime64[us]
heat_days             int64
ice_days              int64
dtype: object

        year  heat_days  ice_days
0 1955-01-01          1        25
1 1956-01-01          3        46
2 1957-01-01         10        20
3 1958-01-01          9        11
4 1959-01-01          5        17

In [9]:
df.head(2)

        year  heat_days  ice_days
0 1955-01-01          1        25
1 1956-01-01          3        46

In [10]:
df.tail(2)

         year  heat_days  ice_days
68 2023-01-01         32         2
69 2024-01-01         45         2

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   year       70 non-null     datetime64[us]
 1   heat_days  70 non-null     int64
 2   ice_days   70 non-null     int64
dtypes: datetime64[us](1), int64(2)
memory usage: 1.8 KB

In [12]:
df.describe()

                             year  heat_days   ice_days
count                          70  70.000000  70.000000
mean   1989-07-02 05:49:42.857142  15.371429  20.414286
min           1955-01-01 00:00:00   0.000000   2.000000
25%           1972-04-01 12:00:00   6.500000  12.250000
50%           1989-07-02 12:00:00  13.000000  19.500000
75%           2006-10-01 18:00:00  21.000000  25.000000
max           2024-01-01 00:00:00  45.000000  63.000000
std                           NaN  11.007470  12.062029

## Daten manipulieren

In [17]:
df["heat_days"]

0      1
1      3
2     10
3      9
4      5
      ..
65    21
66    24
67    31
68    32
69    45
Name: heat_days, Length: 70, dtype: int64

In [18]:
namensliste = ["heat_days", "ice_days"]


df[namensliste]

    heat_days  ice_days
0           1        25
1           3        46
2          10        20
3           9        11
4           5        17
..        ...       ...
65         21         3
66         24         7
67         31         6
68         32         2
69         45         2

[70 rows x 2 columns]

In [19]:
df[["heat_days", "ice_days"]]

    heat_days  ice_days
0           1        25
1           3        46
2          10        20
3           9        11
4           5        17
..        ...       ...
65         21         3
66         24         7
67         31         6
68         32         2
69         45         2

[70 rows x 2 columns]

Restriction

In [26]:
df.loc[df["heat_days"] > 10].loc[df["ice_days"] < 5]

         year  heat_days  ice_days
19 1974-01-01         11         3
60 2015-01-01         42         2
64 2019-01-01         38         3
65 2020-01-01         21         3
68 2023-01-01         32         2
69 2024-01-01         45         2

In [27]:
df.iloc[4]

year         1959-01-01 00:00:00
heat_days                      5
ice_days                      17
Name: 4, dtype: object